<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Form\ProjetType' shared autowired service.

require_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
require_once $this->targetDirs[3].'/src/AppBundle/Form/ProjetType.php';

return $this->services['AppBundle\Form\ProjetType'] = new \AppBundle\Form\ProjetType();
