<?php

namespace Camille\PlatformBundle\Repository;

/**
 * Fiche1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Fiche1Repository extends \Doctrine\ORM\EntityRepository
{
}
