<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\Container0vxwhaz\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/Container0vxwhaz/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\Container0vxwhaz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0vxwhaz\appDevDebugProjectContainer();
